// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Execution fact
export const ERROR_RECEIVE_EXECUTION_FACTS = 'ERROR_RECEIVE_EXECUTION_FACTS';
export const REQUEST_EXECUTION_FACTS = 'REQUEST_EXECUTION_FACTS';
export const RECEIVE_EXECUTION_FACTS = 'RECEIVE_EXECUTION_FACTS';

export const ERROR_DELETE_EXECUTION_FACT = 'ERROR_DELETE_EXECUTION_FACT';
export const REQUEST_DELETE_EXECUTION_FACT = 'REQUEST_DELETE_EXECUTION_FACT';
export const SUCCESS_DELETE_EXECUTION_FACT = 'SUCCESS_DELETE_EXECUTION_FACT';

export const ERROR_GET_EXECUTION_FACT = 'ERROR_GET_EXECUTION_FACT';
export const REQUEST_EXECUTION_FACT = 'REQUEST_EXECUTION_FACT';
export const RECEIVE_EXECUTION_FACT = 'RECEIVE_EXECUTION_FACT';

export const ERROR_SAVE_EXECUTION_FACT = 'ERROR_SAVE_EXECUTION_FACT';
export const REQUEST_SAVE_EXECUTION_FACT = 'REQUEST_SAVE_EXECUTION_FACT';
export const SUCCESS_SAVE_EXECUTION_FACT = 'SUCCESS_SAVE_EXECUTION_FACT';

export const ERROR_UPDATE_EXECUTION_FACT = 'ERROR_UPDATE_EXECUTION_FACT';
export const REQUEST_UPDATE_EXECUTION_FACT = 'REQUEST_UPDATE_EXECUTION_FACT';
export const SUCCESS_UPDATE_EXECUTION_FACT = 'SUCCESS_UPDATE_EXECUTION_FACT';
